// src/pages/Home.jsx
import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white">
            {/* Hero Section */}
            <section className="flex flex-col items-center justify-center text-center py-16 px-4">
                <h1 className="text-4xl md:text-6xl font-extrabold mb-4">
                    Welcome to <span className="text-blue-500">AI Blog</span>
                </h1>
                <p className="text-lg md:text-xl max-w-2xl mb-6">
                    Share your thoughts, explore trending articles, and let AI generate summaries & SEO tags for your blogs.
                </p>
                <div className="flex gap-4">
                    <Link
                        to="/create"
                        className="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg text-white font-semibold"
                    >
                        Start Writing
                    </Link>
                    <Link
                        to="/explore"
                        className="px-6 py-3 bg-gray-200 dark:bg-gray-700 hover:bg-gray-600 rounded-lg font-semibold"
                    >
                        Explore Blogs
                    </Link>
                </div>
            </section>

            {/* Featured Blogs */}
            <section className="max-w-6xl mx-auto px-4 py-12">
                <h2 className="text-2xl font-bold mb-6">Featured Blogs</h2>
                <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                    {[1, 2, 3].map((id) => (
                        <div
                            key={id}
                            className="bg-white dark:bg-gray-800 shadow-md rounded-xl overflow-hidden hover:scale-[1.02] transition-transform"
                        >
                            <img
                                src={`https://picsum.photos/600/400?random=${id}`}
                                alt="blog cover"
                                className="w-full h-48 object-cover"
                            />
                            <div className="p-4">
                                <h3 className="text-lg font-semibold mb-2">
                                    Sample Blog Title {id}
                                </h3>
                                <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                                    This is a short preview of the blog content generated by AI.
                                </p>
                                <Link
                                    to={`/blog/${id}`}
                                    className="text-blue-600 dark:text-blue-400 hover:underline text-sm font-medium"
                                >
                                    Read More →
                                </Link>
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            {/* Footer */}
            <footer className="bg-gray-100 dark:bg-gray-800 text-center py-6 mt-12">
                <p className="text-sm text-gray-600 dark:text-gray-400">
                    © {new Date().getFullYear()} AI Blog. All rights reserved.
                </p>
            </footer>
        </div>
    );
};

export default Home;
